#!/usr/bin/python3

def load_manifest() -> str:
    with open("package_files.txt") as f:
        raw_data = f.readlines()
        tab_data = []
        for i in raw_data:
            tab_data.append(i[:-1].split(" "))
        return tab_data

def mk_scripts(data: list) -> None:
    autogen_msg = "# This is an automatically generated script, please do not edit this file manually.\n\n"
    inst = autogen_msg
    strap = autogen_msg
    uninst = autogen_msg

    files = []
    targets = []
    rmfol = []

    sent_rml = False

    for i in data:
        if i[0] == "folder":
            inst += 'be.based.run("mkdir ' + i[1] + '")\n'
            strap += 'try:\n    mkdir(path.join(root, "' + i[1][1:] + '"))\nexcept FileExistsError:\n    pass\n'
            rmfol.append(i[1])
        elif i[0] == "file":
            inst += 'be.based.run("cp ' + i[1] + ' ' + i[2] + '")\n'
            strap += 'shutil.copy("' + i[1] + '", path.join(root, "' + i[2][1:] + '"))\n'
            if not sent_rml:
                sent_rml = True
                uninst += 'be.based.run("rm'
            uninst += " " + i[2]
        else:
            raise RuntimeError("Unknown command " + str(i[0]) + "!")

    if sent_rml:
        uninst += '")\n'
    rmfol.reverse()
    for i in rmfol:
        uninst += 'be.based.run("rmdir ' + i + '")\n'

    signoff = 'be.api.setvar("return", "0")\n'
    inst += signoff
    strap += signoff
    uninst += signoff

    with open("files/installer.py", "w") as f:
        f.write(inst)
    with open("files/strap.py", "w") as f:
        f.write(strap)
    with open("files/uninstaller.py", "w") as f:
        f.write(uninst)

if __name__ == "__main__":
    manifest = load_manifest()
    mk_scripts(manifest)
